- name: Deploy DockerHub app to Kubernetes
  hosts: launched
  become: yes
  tasks:
    - name: Create Deployment
      copy:
        dest: /tmp/app-deployment.yaml
        content: |
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: sample-app
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: sample-app
            template:
              metadata:
                labels:
                  app: sample-app
              spec:
                containers:
                - name: sample-app
                  image: hassanhbahmed/sample-app:latest
                  ports:
                  - containerPort: 80
    - name: Apply Deployment
      shell: kubectl apply -f /tmp/app-deployment.yaml

    - name: Expose Service
      shell: kubectl expose deployment sample-app --type=NodePort --port=80
